spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "2.0"

cards:
  message: "Welcome to cards related prod APIs "
  contactDetails:
    name: "Tony Stark - Product Owner"
    email: "tonyStark@gmail.com"
  onCallSupport:
    - (666) 666-2345
    - (654) 523-4444