spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "3.0"

cards:
  message: "Welcome to cards related qa APIs "
  contactDetails:
    name: "Hugh Jackman - QA Lead"
    email: "hughJackman@gmail.com"
  onCallSupport:
    - (444) 555-1234
    - (765) 123-4567