services:
  accountsdb:
    image: mysql:latest
    container_name: accountsdb
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_DATABASE: accountsdb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - ms-network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq-ms
    ports:
      - 5672:5672
      - 15672:15672
    deploy:
      resources:
        limits:
          memory: 700m
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - ms-network

  configserver:
    image: khanhnq297288/config-server:jdk17
    container_name: config-server-ms
    ports:
      - 8071:8071
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
    networks:
      - ms-network

  accounts:
    image: khanhnq297288/accounts:jdk17
    container_name: accounts-ms
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      configserver:
        condition: service_started
      accountsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3307/accountsdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - ms-network

networks:
  ms-network:
    driver: "bridge"