services:
  accounts:
    image: khanhnq297288/accounts:jdk17
    container_name: accounts-ms
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ms-network
  cards:
    image: khanhnq297288/cards:jdk17
    container_name: cards-ms
    ports:
      - 8081:8081
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ms-network
  loans:
    image: khanhnq297288/loans:jdk17
    container_name: loans-ms
    ports:
      - 8082:8082
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ms-network
networks:
  ms-network:
    driver: "bridge"