services:
  network-deploy-service:
    networks:
      - ms-network

  microservice-base-config:
    extends:
      network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-configserver-config:
    extends:
      microservice-base-config
    depends_on:
      configserver:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: qa
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"