build:
  version: "2.0"

accounts:
  message: "Welcome to accounts related prod APIs "
  contactDetails:
    name: "Tony Stark - Product Owner"
    email: "tonyStark@gmail.com"
  onCallSupport:
    - (666) 666-2345
    - (654) 523-4444