build:
  version: "1.0"

cards:
  message: "Welcome to cards related default APIs "
  contactDetails:
    name: "Johnny Dept - Developer"
    email: "johnnyDept@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345



