server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
#    (local configuration files)
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///Users//eazybytes//Documents//config"
        git:
          uri: "https://github.com/khanhnq2882/financial-management-microservices-config.git"
          default-label: main
          clone-on-start: true
          force-pull: true
          timeout: 5
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true